language: python
sudo: false
python: 3.6
env:
  - TOX_ENV=py3
  - TOX_ENV=py27
addons:
  apt:
    packages:
    - libmad0
    - libmad0-dev
install: pip install -r requirements_test.txt
script: tox -e $TOX_ENV
